language: ruby
sudo: false
cache: bundler
notifications:
  email: false
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.2.5
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=build
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
addons:
  code_climate:
    repo_token: d1136826acdf477d97daef036acfb77402728f261d664800513c2521a01a05c0
